Add overflow wrapping support
melloware/react-logviewer pull request #55
Opened 2024-11-06 12:40 UTC by HunterCFigueroa

Replaces react-window with virtua. Virtua has a some really nice autosizing built in which opens up the opportunity for overflow wrapping.

Not sure if the passed down wrapLines prop is the ideal approach but it gets the job done.

2024-11-06 12:50 UTC, melloware requested changes

2024-11-06 12:50 UTC, melloware commented on package.json
>          "react-virtualized-auto-sizer": "^1.0.24",
Can we also remove `react-virtualized-auto-sizer`?

2024-11-06 12:50 UTC, melloware commented on src/components/LazyLog/index.tsx
> +                    style={{ height: 800 }}
Hardcoded 800? Instead of calculateListHeight?

2024-11-06 12:50 UTC, melloware commented on src/components/LazyLog/index.tsx
> -                                onScroll={(options) => {
It looks like you removed onScroll and the ability for users to attach to onScroll event?  Also what about ScrollFollowing?

2024-11-06 12:54 UTC, HunterCFigueroa commented on src/components/LazyLog/index.tsx
> +                    style={{ height: 800 }}
Yeah, that was just for getting the POC up and running. Now that I know there's interest Ill spend some time cleaning it up.

2024-11-06 12:55 UTC, melloware commented
Also to answer your question about `wrapLines` bubbling down that is the style of the component when I took it over so i like that you kept that pattern.    Overall i feel like your changes will be a big improvement as Virtua looks pretty impressive.

2024-11-06 13:04 UTC, melloware commented
Also it looks like Virtua has some nice features to replace current features of React Window:

ScrollTo: https://inokawa.github.io/virtua/?path=/story/basics-vlist--scroll-to
Scroll Restoration: https://inokawa.github.io/virtua/?path=/story/basics-vlist--scroll-restoration
Infinite Scrolling: https://inokawa.github.io/virtua/?path=/story/basics-vlist--infinite-scrolling

2024-11-06 15:01 UTC, HunterCFigueroa commented
Alright i think i got it all working, but you would know better than me lol

2024-11-06 16:17 UTC, melloware commented
This is great let me do some testing!

2024-11-07 20:28 UTC, melloware commented
In the highlighting and scrolling example the correct values are being highlihgted but not automatically scrolled to.

See:
![image](https://github.com/user-attachments/assets/d1365fd2-9584-4126-94bc-ff8254eb4a29)

compare with: https://melloware.github.io/react-logviewer/?path=/story/stories-lazylog--highlight-and-scrolling

2024-11-08 00:53 UTC, melloware requested changes
See comments

2024-11-08 03:25 UTC, HunterCFigueroa commented
Nice catch 🐟

2024-11-08 13:48 UTC, melloware commented
also any chance you could add a new storybook showing the line wrapping on?

2024-11-08 13:59 UTC, melloware commented
This is looking pretty good so far i think this will be a good long term change to the component!

2024-11-08 14:55 UTC, melloware commented
ok nice!  Is this safe for me to re-review?

2024-11-08 14:57 UTC, melloware requested changes

2024-11-08 14:57 UTC, melloware commented on src/components/LazyLog/index.module.css
> +.wrap {
```suggestion
.wrapLine {
```

2024-11-08 14:57 UTC, melloware commented on src/components/LazyLog/index.module.css.d.ts
> +        wrap: string;
```suggestion
        wrapLine: string;
```

2024-11-08 14:57 UTC, melloware commented on src/components/LazyLog/index.tsx
> +        wrapLines: true,
Move this down after the last `enable` so its not mixed in the middle and more alpha order?

2024-11-08 17:59 UTC, HunterCFigueroa commented on src/components/LazyLog/index.tsx
> +        wrapLines: true,
Would you like it disabled by default?

2024-11-08 18:06 UTC, HunterCFigueroa commented
Ready for re-review @melloware

2024-11-08 21:16 UTC, melloware commented on src/components/LazyLog/index.tsx
> +        wrapLines: true,
Yes disabled by default would be ideal.

2024-11-08 21:17 UTC, melloware approved these changes

2024-11-08 21:18 UTC, melloware commented
I think this is good enough to merge.  Did you want to look at https://github.com/melloware/react-logviewer/issues/8 next since i think now it can be supported easily with Virtua?

2024-11-08 21:18 UTC, merged

2024-11-08 21:20 UTC, HunterCFigueroa commented
Sure, I can take a look

2024-11-08 22:09 UTC, melloware commented
also can you check the HTML links example?  I am not sure why the spacing is so wide and whether it was before?

![image](https://github.com/user-attachments/assets/7440689c-0a18-4d1d-a997-41c54c594c58)

2024-11-08 22:56 UTC, HunterCFigueroa commented
Yeah it wasn't like that before, looking now